# Comment out shell script individually if app is not needed!

Apps/installAlacritty.sh
wait
Apps/installBalenaEtcher.sh
wait
Apps/installBlender.sh
wait
Apps/installChrome.sh
wait
Apps/installDestreamer.sh
wait
Apps/installDiscord.sh
wait
Apps/installDmenu.sh
wait
Apps/installDoomnvim.sh
wait
Apps/installFirefox.sh
wait
Apps/installFlameshot.sh
wait
Apps/FoxitReader.sh
wait
Apps/installJabRef.sh
wait
Apps/installLibreoffice.sh
wait
Apps/installMEGA.sh
wait
Apps/installMixxx.sh
wait
Apps/installNitrogen.sh
wait
Apps/installOBS.sh
wait
Apps/installQtractor.sh
wait
Apps/installRClone.sh
wait
Apps/installSignal.sh
wait
Apps/installSpotify.sh
wait
Apps/installStacer.sh
wait
Apps/installStGallenSteuern.sh
wait
Apps/installTeams.sh
wait
Apps/installTexMaker.sh
wait
Apps/installThunderBird.sh
wait
Apps/installUltimakerCura.sh
wait
Apps/installVLC.sh
wait
Apps/installVNCViewer.sh
wait
Apps/installWhatsApp.sh
wait
