Apps/installBalenaEtcher.sh
wait
Apps/installBlender.sh
wait
Apps/installChrome.sh
wait
Apps/installDiscord.sh
wait
Apps/installGNOMETweaks.sh
wait
Apps/installIriunWebcam.sh
wait
Apps/installJabRef.sh
wait
Apps/installLibreOffice.sh
wait
Apps/installMEGA.sh
wait
Apps/installMixxx.sh
wait
Apps/installOBS.sh
wait
Apps/installOneDrive.sh
wait
Apps/installQtractor.sh
wait
Apps/installSignal.sh
wait
Apps/installSpotify.sh
wait
Apps/installStacer.sh
wait
Apps/installStGallenSteuern.sh
wait
Apps/installTeams.sh
wait
Apps/installTexMaker.sh
wait
Apps/installThunderbird.sh
wait
Apps/installUltimakerCura.sh
wait
Apps/installVisualStudioCode.sh
wait
Apps/installVLC.sh
wait
Apps/installVNCViewer.sh
wait
Apps/installWhatsApp.sh
wait