Packages/installyay.sh
wait
Packages/installffmpeg.sh
wait
Packages/installFlathub.sh
wait
Packages/installGit.sh
wait
Packages/installHtop.sh
wait
Packages/installNeofetch.sh
wait
Packages/installNode.sh
wait
Packages/installQpdf.sh
wait
Packages/installsnd_hda_macbookpro.sh
wait
Packages/installThefuck.sh
wait
Packages/Other/installFedoraWorkstationRepositories.sh
wait